INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Arno', 22.8,'male' );
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('George', 25.5,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Michiel', 24.6,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Peter', 23.8,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Sylvia', 29.2,'female');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Jan', 26.5,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Bram', 23.2,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Ruud', 44.0,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Leon', 18.4,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Bart', 24.9,'male');
INSERT INTO golfers(`name`, `handicap`, `gender`) VALUES('Ornella', 39.0,'female');
